import { useState, useEffect } from "react";
import { MainLayout } from "@/components/layout/MainLayout";
import FileUploader from "@/components/shared/FileUploader";
import FFmpegCommandDisplay from "@/components/shared/FFmpegCommandDisplay"; // Added back
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button"; // Import Button
import { Loader2 } from "lucide-react"; // Import Loader2 icon
import { useFFmpegProcessor } from "@/hooks/useFFmpegProcessor"; // Import the new hook
import OutputMediaPlayer from "@/components/shared/OutputMediaPlayer"; // Import the new component
import { toast } from "sonner"; // Import toast
import type { SingleFileCommandPayload } from "@/hooks/useFFmpegProcessor"; // Import payload type


const BitstreamExtractor = () => {
  // Use the new hook
  const {
    selectedFiles, // Keep selectedFiles from hook for UI logic
    uploadedFilename, // Keep for potential display/debugging, but logic relies on return values from upload functions
    outputFile,
    isUploading,
    isProcessing,
    mediaError,
    generatedCommand, // Get the generated command from the hook
    handleFileSelect, // Use the hook's file select handler
    runCommand, // Use the hook's run command handler
    setCommand, // Use the hook's set command function
    setMediaError, // Pass the hook's setMediaError to the player
    uploadSingleFile, // Import the explicit upload function
  } = useFFmpegProcessor();

  const [selectedStreamType, setSelectedStreamType] = useState<"video" | "audio" | "subtitles" | "">("");

  const streamTypeOptions = [
    { label: "Video Stream", value: "video" },
    { label: "Audio Stream", value: "audio" },
    { label: "Subtitle Stream", value: "subtitles" },
    // Add more if needed
  ];

  // Effect to generate command string for display whenever selectedFiles or selectedStreamType changes
  // This command string uses the *local* file name for display purposes.
  useEffect(() => {
      if (selectedFiles.length === 1 && selectedStreamType) {
          generateDisplayCommandString(selectedFiles[0].name, selectedStreamType);
      } else {
          setCommand(""); // Clear command if requirements aren't met
      }
  }, [selectedFiles, selectedStreamType, setCommand]); // Add setCommand to dependencies


  const handleStreamTypeChange = (value: "video" | "audio" | "subtitles" | "") => {
    setSelectedStreamType(value);
    // Command will be regenerated by the useEffect hook
  };

  // Function to generate the command string for display (used by useEffect)
  // This uses the *local* file name for display purposes.
  const generateDisplayCommandString = (inputFilename: string, streamType: "video" | "audio" | "subtitles" | "") => {
    if (!inputFilename || !streamType) {
      return ""; // Return empty string if command cannot be generated
    }

    const baseName = inputFilename.split('.')[0];
    let mapOption = "";
    let outputExtension = "";

    switch (streamType) {
        case "video":
            mapOption = "0:v";
            outputExtension = "h264"; // Common raw video bitstream extension
            break;
        case "audio":
            mapOption = "0:a";
            outputExtension = "aac"; // Common raw audio bitstream extension (depends on original codec)
            break;
        case "subtitles":
            mapOption = "0:s";
            outputExtension = "srt"; // Common subtitle format (extraction often converts)
            break;
        default:
            setCommand("");
            return ""; // Should not happen with valid streamType
    }

    const outputFileName = `${baseName}_extracted.${outputExtension}`;

    // Use -map to select the stream and -c copy to copy the raw bitstream
    const command = `ffmpeg -i "${inputFilename}" -map ${mapOption} -c copy "${outputFileName}"`;

    setCommand(command); // Set the command using the hook's function
    return command; // Return the generated command string
  };

  // New handler for the Run button
  const handleRunClick = async () => {
      if (selectedFiles.length === 0) {
          toast.warning("Please select a file first.");
          return;
      }
      if (selectedFiles.length > 1) {
          toast.warning("Bitstream Extraction currently only supports a single file. Please select only one file.");
          return;
      }
      if (!selectedStreamType) {
          toast.warning("Please select a stream type (Video, Audio, or Subtitles).");
          return;
      }

      // Explicitly trigger single file upload
      const uploadedFile = await uploadSingleFile(selectedFiles[0]);

      if (uploadedFile) {
          // Construct the actual command payload using the *uploaded* filename
          const actualCommand = generateDisplayCommandString(uploadedFile, selectedStreamType); // Reuse logic, but pass uploadedFile

          const payload: SingleFileCommandPayload = {
              command: actualCommand,
              inputFile: uploadedFile, // Use the uploaded filename
          };
          runCommand(payload); // Run the command via the hook
      }
  };


  return (
    <MainLayout>
      <div className="flex-1 space-y-4 p-8 pt-6">
        <h2 className="text-3xl font-bold tracking-tight">Bitstream Extractor</h2>
        <p className="text-muted-foreground">Generate FFmpeg commands to extract raw video, audio, or subtitle bitstreams.</p>

        {/* Use the hook's file select handler */}
        <FileUploader onFileSelect={(files) => {
          setMediaError(null);         // clear error/output state
          setCommand("");              // clear old command
          setSelectedStreamType("");   // clear stream type selection
          handleFileSelect(files);     // call the hook
        }} />

        {selectedFiles.length > 0 && ( // Use hook's selectedFiles for UI visibility
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Extraction Options</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">

               {isUploading && (
                   <p className="text-sm text-blue-600">Uploading file...</p>
               )}

               {/* Render options only after initial file selection and not uploading */}
               {!isUploading && selectedFiles.length > 0 && (
                   <>
                       {/* Display selected files */}
                       <div>
                           <h4 className="text-md font-semibold mb-2">Selected File(s):</h4>
                           <ul>
                               {selectedFiles.map((file, index) => (
                                   <li key={index} className="text-sm text-muted-foreground">{file.name}</li>
                               ))}
                           </ul>
                       </div>

                       {selectedFiles.length > 1 && (
                           <p className="text-sm text-yellow-600">Note: Extraction currently only applies to the first selected file.</p>
                       )}

                       <div className="grid w-full max-w-sm items-center gap-1.5">
                         <Label htmlFor="stream-type-select">Stream Type</Label>
                          <Select
                            onValueChange={handleStreamTypeChange}
                            value={selectedStreamType}
                            disabled={isProcessing || isUploading}
                          >
                            <SelectTrigger id="stream-type-select">
                              <SelectValue placeholder="Select Stream Type" />
                            </SelectTrigger>
                            <SelectContent>
                              {streamTypeOptions.map(option => (
                                <SelectItem key={option.value} value={option.value}>
                                  {option.label}
                                </SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                       </div>

                       {/* Run Button - uses the new handleRunClick */}
                       <Button
                           onClick={handleRunClick} // Use the new handler
                           disabled={!selectedStreamType || selectedFiles.length === 0 || isProcessing || isUploading} // Disable if options not selected, no file, processing, or uploading
                       >
                           {isProcessing ? (
                               <>
                                   <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                   Processing...
                               </>
                           ) : isUploading ? (
                               <>
                                   <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                   Uploading...
                               </>
                           ) : (
                               "Run Extraction"
                           )}
                       </Button>
                       <p className="text-sm text-yellow-600">
                           Note: Clicking "Run" will first upload the selected file and then send the command to your local backend server running on http://localhost:8200.
                           Ensure your backend is running and has access to the selected file.
                       </p>
                       <p className="text-sm text-yellow-600">
                           Note: This tool generates a command to extract the *first* stream of the selected type (`-map 0:v`, `0:a`, or `0:s`). To extract specific streams (e.g., the second audio track), you need to know the stream index (e.g., `-map 0:a:1`). Executing the command requires FFmpeg installed on your system.
                       </p>
                   </>
               )}

            </CardContent>
          </Card>
        )}

        {/* Use the new OutputMediaPlayer component */}
        <OutputMediaPlayer outputFile={outputFile} mediaError={mediaError} setMediaError={setMediaError} />

        {/* FFmpegCommandDisplay component is now added back */}
        <FFmpegCommandDisplay command={generatedCommand} />

      </div>
    </MainLayout>
  );
};

export default BitstreamExtractor;