import { useState, useEffect } from "react";
import { MainLayout } from "@/components/layout/MainLayout";
import FileUploader from "@/components/shared/FileUploader";
import FFmpegCommandDisplay from "@/components/shared/FFmpegCommandDisplay"; // Added back
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Button } from "@/components/ui/button"; // Import Button
import { Loader2 } from "lucide-react"; // Import Loader2 icon
import { useFFmpegProcessor } from "@/hooks/useFFmpegProcessor"; // Import the new hook
import OutputMediaPlayer from "@/components/shared/OutputMediaPlayer"; // Import the new component
import { toast } from "sonner"; // Import toast
import type { SingleFileCommandPayload } from "@/hooks/useFFmpegProcessor"; // Import payload type


const MotionInterpolator = () => {
  // Use the new hook
  const {
    selectedFiles, // Keep selectedFiles from hook for UI logic
    uploadedFilename, // Keep for potential display/debugging, but logic relies on return values from upload functions
    outputFile,
    isUploading,
    isProcessing,
    mediaError,
    generatedCommand, // Get the generated command from the hook
    handleFileSelect, // Use the hook's file select handler
    runCommand, // Use the hook's run command handler
    setCommand, // Use the hook's set command function
    setMediaError, // Pass the hook's setMediaError to the player
    uploadSingleFile, // Import the explicit upload function
  } = useFFmpegProcessor();

  const [outputFps, setOutputFps] = useState<string>("");
  const [interpolationMode, setInterpolationMode] = useState<string>("");

  const fpsOptions = ["", "60", "120", "240"]; // Example FPS options
  const modeOptions = [
    { label: "Select Mode", value: "" },
    { label: "Blend", value: "blend" }, // Simple blending
    { label: "Duplicate", value: "dup" }, // Duplicate frames
    // More advanced modes like 'mci', 'scd' require libmysofa or other dependencies
    // { label: "Motion Compensated", value: "mci" },
  ];

  // Effect to generate command string for display whenever selectedFiles, fps, or mode changes
  // This command string uses the *local* file name for display purposes.
  useEffect(() => {
      if (selectedFiles.length === 1 && outputFps && interpolationMode) {
          generateDisplayCommandString(selectedFiles[0].name, outputFps, interpolationMode);
      } else {
          setCommand(""); // Clear command if requirements aren't met
      }
  }, [selectedFiles, outputFps, interpolationMode, setCommand]); // Add setCommand to dependencies


  const handleFpsChange = (value: string) => {
    setOutputFps(value);
    // Command will be regenerated by the useEffect hook
  };

  const handleModeChange = (value: string) => {
    setInterpolationMode(value);
    // Command will be regenerated by the useEffect hook
  };

  // Function to generate the command string for display (used by useEffect)
  // This uses the *local* file name for display purposes.
  const generateDisplayCommandString = (inputFilename: string, fps: string, mode: string) => {
    if (!inputFilename || !fps || !mode) {
      return ""; // Return empty string if command cannot be generated
    }

    // Basic command generation (single file for now)
    const baseName = inputFilename.split('.')[0];
    const outputFileName = `${baseName}_${fps}fps_${mode}.${inputFilename.split('.').pop()}`; // Simple output naming

    // Use the minterpolate filter
    // Note: minterpolate can be complex and may require specific FFmpeg builds or libraries.
    // This is a basic example using common modes.
    const command = `ffmpeg -i "${inputFilename}" -vf "minterpolate=fps=${fps}:mi_mode=${mode}" -c:a copy "${outputFileName}"`;

    setCommand(command); // Set the command using the hook's function
    return command; // Return the generated command string
  };

  // New handler for the Run button
  const handleRunClick = async () => {
      if (selectedFiles.length === 0) {
          toast.warning("Please select a file first.");
          return;
      }
      if (selectedFiles.length > 1) {
          toast.warning("Motion Interpolation currently only supports a single file. Please select only one file.");
          return;
      }
      if (!outputFps) {
          toast.warning("Please select an output frame rate.");
          return;
      }
      if (!interpolationMode || interpolationMode === "Select Mode") {
          toast.warning("Please select an interpolation mode.");
          return;
      }

      // Explicitly trigger single file upload
      const uploadedFile = await uploadSingleFile(selectedFiles[0]);

      if (uploadedFile) {
          // Construct the actual command payload using the *uploaded* filename
          const actualCommand = generateDisplayCommandString(uploadedFile, outputFps, interpolationMode); // Reuse logic, but pass uploadedFile

          const payload: SingleFileCommandPayload = {
              command: actualCommand,
              inputFile: uploadedFile, // Use the uploaded filename
          };
          runCommand(payload); // Run the command via the hook
      }
  };


  return (
    <MainLayout>
      <div className="flex-1 space-y-4 p-8 pt-6">
        <h2 className="text-3xl font-bold tracking-tight">Motion Interpolation</h2>
        <p className="text-muted-foreground">Smooth out video by interpolating frames to increase frame rate.</p>

        {/* Use the hook's file select handler */}
        <FileUploader onFileSelect={handleFileSelect} />

        {selectedFiles.length > 0 && ( // Use hook's selectedFiles for UI visibility
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Interpolation Options</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">

               {isUploading && (
                   <p className="text-sm text-blue-600">Uploading file...</p>
               )}

               {/* Render options only after initial file selection and not uploading */}
               {!isUploading && selectedFiles.length > 0 && (
                   <>
                       {/* Display selected files */}
                       <div>
                           <h4 className="text-md font-semibold mb-2">Selected File(s):</h4>
                           <ul>
                               {selectedFiles.map((file, index) => (
                                   <li key={index} className="text-sm text-muted-foreground">{file.name}</li>
                               ))}
                           </ul>
                       </div>

                       {selectedFiles.length > 1 && (
                           <p className="text-sm text-yellow-600">Note: Motion interpolation currently only applies to the first selected file.</p>
                       )}

                       <div className="grid w-full max-w-sm items-center gap-1.5">
                         <Label htmlFor="output-fps-select">Output Frame Rate (FPS)</Label>
                         <Select onValueChange={handleFpsChange} value={outputFps} disabled={isProcessing || isUploading}>
                           <SelectTrigger id="output-fps-select">
                             <SelectValue placeholder="Select FPS" />
                           </SelectTrigger>
                           <SelectContent>
                             {fpsOptions.map(fps => (
                               <SelectItem key={fps} value={fps}>{fps || "Select FPS"}</SelectItem>
                             ))}
                           </SelectContent>
                         </Select>
                       </div>

                        <div className="grid w-full max-w-sm items-center gap-1.5">
                          <Label htmlFor="interpolation-mode-select">Interpolation Mode</Label>
                          <Select onValueChange={handleModeChange} value={interpolationMode} disabled={isProcessing || isUploading}>
                            <SelectTrigger id="interpolation-mode-select">
                              <SelectValue placeholder="Select mode" />
                            </SelectTrigger>
                            <SelectContent>
                              {modeOptions.map(option => (
                                <SelectItem key={option.value} value={option.value}>{option.label}</SelectItem>
                              ))}
                            </SelectContent>
                          </Select>
                        </div>

                       {/* Run Button - uses the new handleRunClick */}
                       <Button
                           onClick={handleRunClick} // Use the new handler
                           disabled={!outputFps || !interpolationMode || interpolationMode === "Select Mode" || selectedFiles.length === 0 || isProcessing || isUploading} // Disable if options not selected, no file, processing, or uploading
                       >
                           {isProcessing ? (
                               <>
                                   <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                   Processing...
                               </>
                           ) : isUploading ? (
                               <>
                                   <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                   Uploading...
                               </>
                           ) : (
                               "Run Interpolation"
                           )}
                       </Button>
                       <p className="text-sm text-yellow-600">
                           Note: Clicking "Run" will first upload the selected file and then send the command to your local backend server running on http://localhost:8200.
                           Ensure your backend is running and has access to the selected file.
                       </p>
                       <p className="text-sm text-yellow-600">
                           Note: The `minterpolate` filter can be computationally intensive and may require specific FFmpeg builds or external libraries for advanced modes.
                       </p>
                   </>
               )}

            </CardContent>
          </Card>
        )}

        {/* Use the new OutputMediaPlayer component */}
        <OutputMediaPlayer outputFile={outputFile} mediaError={mediaError} setMediaError={setMediaError} />

        {/* FFmpegCommandDisplay component is now added back */}
        <FFmpegCommandDisplay command={generatedCommand} />

      </div>
    </MainLayout>
  );
};

export default MotionInterpolator;