import { useState, useEffect } from "react";
import { MainLayout } from "@/components/layout/MainLayout";
import FileUploader from "@/components/shared/FileUploader";
import FFmpegCommandDisplay from "@/components/shared/FFmpegCommandDisplay"; // Added back
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ToggleGroup, ToggleGroupItem } from "@/components/ui/toggle-group";
import { Button } from "@/components/ui/button"; // Import Button
import { Loader2 } from "lucide-react"; // Import Loader2 icon
import { useFFmpegProcessor } from "@/hooks/useFFmpegProcessor"; // Import the new hook
import OutputMediaPlayer from "@/components/shared/OutputMediaPlayer"; // Import the new component
import { toast } from "sonner"; // Import toast
import type { SingleFileCommandPayload } from "@/hooks/useFFmpegProcessor"; // Import payload type


const StreamExtractor = () => {
  // Use the new hook
  const {
    selectedFiles, // Keep selectedFiles from hook for UI logic
    uploadedFilename, // Keep for potential display/debugging, but logic relies on return values from upload functions
    outputFile,
    isUploading,
    isProcessing,
    mediaError,
    generatedCommand, // Get the generated command from the hook
    handleFileSelect, // Use the hook's file select handler
    runCommand, // Use the hook's run command handler
    setCommand, // Use the hook's set command function
    setMediaError, // Pass the hook's setMediaError to the player
    uploadSingleFile, // Import the explicit upload function
  } = useFFmpegProcessor();

  const [extractionType, setExtractionType] = useState<"audio" | "video" | "">("");
  const [outputFormat, setOutputFormat] = useState<string>("");

  // Placeholder options - replace with actual logic later
  const audioFormats = ["mp3", "wav", "aac", "flac"];
  const videoFormats = ["mp4", "mkv", "mov"]; // Formats suitable for video stream extraction

  // Effect to generate command string for display whenever selectedFiles, type, or format changes
  // This command string uses the *local* file name for display purposes.
  useEffect(() => {
      if (selectedFiles.length === 1 && extractionType && outputFormat) {
          generateDisplayCommandString(selectedFiles[0].name, extractionType, outputFormat);
      } else {
          setCommand(""); // Clear command if requirements aren't met
      }
  }, [selectedFiles, extractionType, outputFormat, setCommand]); // Add setCommand to dependencies


  const handleTypeChange = (value: "audio" | "video" | "") => {
    setExtractionType(value);
    // Reset format when type changes
    setOutputFormat("");
    // Command will be regenerated by the useEffect hook
  };

  const handleFormatChange = (value: string) => {
    setOutputFormat(value);
    // Command will be regenerated by the useEffect hook
  };

  // Function to generate the command string for display (used by useEffect)
  // This uses the *local* file name for display purposes.
  const generateDisplayCommandString = (inputFilename: string, type: "audio" | "video" | "", format: string) => {
    if (!inputFilename || !type || !format) {
      return ""; // Return empty string if command cannot be generated
    }

    // Use the uploaded filename for the input
    const outputFile = `${inputFilename.split('.')[0]}_extracted.${format}`;
    let command = `ffmpeg -i "${inputFilename}"`;

    if (type === "audio") {
      command += ` -vn`; // Remove video stream
      // Select audio codec based on output format for re-encoding
      switch (format) {
          case "mp3":
              command += ` -acodec libmp3lame -ab 192k`; // Re-encode to MP3 192kbps
              break;
          case "wav":
              command += ` -acodec pcm_s16le`; // Re-encode to uncompressed PCM
              break;
          case "aac":
              command += ` -acodec aac`; // Re-encode to AAC
              break;
          case "flac":
              command += ` -acodec flac`; // Re-encode to FLAC
              break;
          default:
              // Fallback or error handling if format is unexpected
              console.error(`Unsupported audio format for re-encoding: ${format}`);
              setCommand(""); // Clear command if format is not handled
              return ""; // Return empty string
      }
    } else if (type === "video") {
      command += ` -an -vcodec copy`; // Remove audio stream, copy video stream (usually safe for video containers)
    }

    command += ` "${outputFile}"`;
    setCommand(command); // Set the command using the hook's function
    return command; // Return the generated command string
  };

  // New handler for the Run button
  const handleRunClick = async () => {
      if (selectedFiles.length === 0) {
          toast.warning("Please select a file first.");
          return;
      }
      if (selectedFiles.length > 1) {
          toast.warning("Stream Extraction currently only supports a single file. Please select only one file.");
          return;
      }
      if (!extractionType) {
          toast.warning("Please select an extraction type (Audio or Video).");
          return;
      }
       if (!outputFormat) {
          toast.warning("Please select an output format.");
          return;
      }


      // Explicitly trigger single file upload
      const uploadedFile = await uploadSingleFile(selectedFiles[0]);

      if (uploadedFile) {
          // Construct the actual command payload using the *uploaded* filename
          const actualCommand = generateDisplayCommandString(uploadedFile, extractionType, outputFormat); // Reuse logic, but pass uploadedFile

          const payload: SingleFileCommandPayload = {
              command: actualCommand,
              inputFile: uploadedFile, // Use the uploaded filename
          };
          runCommand(payload); // Run the command via the hook
      }
  };


  return (
    <MainLayout>
      <div className="flex-1 space-y-4 p-8 pt-6">
        <h2 className="text-3xl font-bold tracking-tight">Stream Extraction</h2>
        <p className="text-muted-foreground">Extract audio or video streams from a media file.</p>

        {/* Use the hook's file select handler */}
        <FileUploader onFileSelect={handleFileSelect} />

        {selectedFiles.length > 0 && ( // Use hook's selectedFiles for UI visibility
          <Card className="w-full">
            <CardHeader>
              <CardTitle>Extraction Options</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">

               {isUploading && (
                   <p className="text-sm text-blue-600">Uploading file...</p>
               )}

               {/* Render options only after initial file selection and not uploading */}
               {!isUploading && selectedFiles.length > 0 && (
                   <>
                       {/* Display selected files */}
                       <div>
                           <h4 className="text-md font-semibold mb-2">Selected File(s):</h4>
                           <ul>
                               {selectedFiles.map((file, index) => (
                                   <li key={index} className="text-sm text-muted-foreground">{file.name}</li>
                               ))}
                           </ul>
                       </div>

                       {selectedFiles.length > 1 && (
                           <p className="text-sm text-yellow-600">Note: Stream Extraction currently only supports a single file. Only the first file will be processed.</p>
                       )}

                       <div className="grid w-full max-w-sm items-center gap-1.5">
                         <Label>Extraction Type</Label>
                         <ToggleGroup type="single" value={extractionType} onValueChange={(value: "audio" | "video") => handleTypeChange(value)} disabled={isProcessing || isUploading}>
                           <ToggleGroupItem value="audio" aria-label="Toggle audio extraction">
                             Audio
                           </ToggleGroupItem>
                           <ToggleGroupItem value="video" aria-label="Toggle video extraction">
                             Video
                           </ToggleGroupItem>
                         </ToggleGroup>
                       </div>


                      {extractionType && (
                         <div className="grid w-full max-w-sm items-center gap-1.5">
                           <Label htmlFor="output-format">Output Format</Label>
                           <Select onValueChange={handleFormatChange} value={outputFormat} disabled={isProcessing || isUploading}>
                             <SelectTrigger id="output-format">
                               <SelectValue placeholder="Select output format" />
                             </SelectTrigger>
                             <SelectContent>
                               {(extractionType === "audio" ? audioFormats : videoFormats).map(format => (
                                 <SelectItem key={format} value={format}>{format.toUpperCase()}</SelectItem>
                               ))}
                             </SelectContent>
                           </Select>
                         </div>
                      )}

                       {/* Run Button - uses the new handleRunClick */}
                       <Button
                           onClick={handleRunClick} // Use the new handler
                           disabled={!extractionType || !outputFormat || selectedFiles.length === 0 || isProcessing || isUploading} // Disable if options not selected, no file, processing, or uploading
                       >
                           {isProcessing ? (
                               <>
                                   <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                   Processing...
                               </>
                           ) : isUploading ? (
                               <>
                                   <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                                   Uploading...
                               </>
                           ) : (
                               "Run Extraction"
                           )}
                       </Button>
                       <p className="text-sm text-yellow-600">
                           Note: Clicking "Run" will first upload the selected file and then send the command to your local backend server running on http://localhost:8200.
                           Ensure your backend is running and has access to the selected file.
                       </p>
                   </>
               )}

            </CardContent>
          </Card>
        )}

        {/* Use the new OutputMediaPlayer component */}
        <OutputMediaPlayer outputFile={outputFile} mediaError={mediaError} setMediaError={setMediaError} />

        {/* FFmpegCommandDisplay component is now added back */}
        <FFmpegCommandDisplay command={generatedCommand} />

      </div>
    </MainLayout>
  );
};

export default StreamExtractor;